_target_: src.models.segmentation.modules.encoders.tmr.TMRMotionEncoder
weights_path: ./models/tmr_humanml3d_guoh3dfeats/last_weights/motion_encoder.pt
frozen: false
pretrained: false
sample_mean: false
dropout: 0.4
