_target_: src.model.modules.span_representation_layers.ConvolutionalSpanRepresentationLayer
# motion_embed_dim: ${model.motion_frames_encoder.embed_dim}
motion_embed_dim: 256
# representation_dim: ${model.prompt_representation_layer.representation_dim}
representation_dim: 256
max_span_width: 16
min_span_width: 16
step: 1
mode: 'max'
dropout: 0.4
