_target_: src.model.modules.prompts_tokens_encoders.tmr.TMRPromptsTokensEncoder
frozen: false
pretrained: false
weights_path: /home/nadir/motion-linner/models/tmr_humanml3d_guoh3dfeats/last_weights/text_encoder.pt
