_target_: src.model.modules.prompts_tokens_encoders.tmr.TMRPromptsTokensEncoder
weights_path: ./models/tmr_humanml3d_guoh3dfeats/last_weights/text_encoder.pt
pretrained: true
frozen: false
hidden_dimension: 256
