_target_: src.model.MoLiNER

lr: 1e-4

defaults:
  - tokenizer: deberta

  - pair_scorer: dot_product

  # - motion_frames_encoder: tmr
  - motion_frames_encoder: pretrained_tmr
  - prompts_tokens_encoder: transformer
  # - prompts_tokens_encoder: pretrained_tmr

  - spans_generator: static

  - prompt_tokens_aggregator: special_token
  - span_frames_aggregator: concat

  - prompt_representation_layer: mlp
  - span_representation_layer: mlp

  - decoder: generic

pair_scorer: ???

motion_frames_encoder: ???
prompts_tokens_encoder: ???

spans_generator: ???

prompt_tokens_aggregator: ???
span_frames_aggregator: ???

prompt_representation_layer: ???
span_representation_layer: ???

decoder: ???
