_target_: src.model.MoLiNER

lr:
  scratch: 5e-5
  pretrained: 1e-5

defaults:
  # tmr/scratch, tmr/pretrained, tmr/frozen
  - motion_frames_encoder: tmr/frozen
  # deberta/frozen, deberta/pretrained, tmr/scratch, tmr/pretrained, tmr/frozen, clip/frozen, clip/pretrained
  - prompts_tokens_encoder: deberta/frozen

  #  windowed/16, windowed/8, static/16
  - spans_generator: windowed/16

  # mlp/deberta, mlp/tmr, mlp/clip
  - prompt_representation_layer: mlp/deberta
  # transformer, endpoints, query, lstm, convolution, pooling/min, pooling/mean, pooling/max
  - span_representation_layer: endpoints

  # product
  - scorer: product

  # greedy/flat, greedy/nested, greedy/overlap
  - decoder: greedy/overlap
