_target_: src.model.MoLiNER

lr: 1e-4

defaults:
  - pair_scorer: dot_product

  # NOTE: tmr/scratch, tmr/pretrained, tmr/frozen
  - motion_frames_encoder: tmr/scratch
  # NOTE: deberta, tmr/scratch, tmr/pretrained, tmr/frozen, clip
  - prompts_tokens_encoder: deberta

  # NOTE:  windowed/16, windowed/8, static/16
  - spans_generator: windowed/16

  # NOTE: mlp/deberta, mlp/tmr, mlp/clip
  - prompt_representation_layer: mlp/deberta
  - span_representation_layer: mlp

  - decoder: generic
