_target_: src.model.MoLiNER

lr: 1e-4

defaults:
  - tokenizer: deberta

  - pair_scorer: dot_product

  - motion_frames_encoder: pretrained_tmr
  - prompts_tokens_encoder: transformer

  - spans_generator: static

  - span_frames_aggregator: concat

  - prompt_representation_layer: mlp
  - span_representation_layer: mlp

  - decoder: generic
