_target_: src.model.MoLiNER

lr: 1e-4

defaults:
  - tokenizer: pretrained_tmr

  - pair_scorer: dot_product

  - motion_frames_encoder: pretrained_tmr
  - prompts_tokens_encoder: pretrained_tmr

  - spans_generator: 16_windowed

  - prompt_tokens_aggregator: special_token
  - span_frames_aggregator: concat

  - prompt_representation_layer: mlp
  - span_representation_layer: mlp

  - decoder: generic
