_target_: src.model.MoLiNER

defaults:
  # tmr/scratch, tmr/pretrained, tmr/frozen
  - motion_frames_encoder: tmr/scratch
  # deberta/frozen, deberta/pretrained, tmr/scratch, tmr/pretrained, tmr/frozen, clip/frozen, clip/pretrained
  - prompts_tokens_encoder: tmr/scratch

  #  windowed/16, windowed/8, static/1-16, static/1-32, static/8-32, static/1-64
  - spans_generator: static/1-32

  # mlp/deberta, mlp/tmr, mlp/clip
  - prompt_representation_layer: mlp/tmr
  # endpoints
  # convolution/base/16-16, convolution/max/16-16, convolution/sum/16-16, convolution/mean/16-16
  - span_representation_layer: endpoints

  # product
  - scorer: product

  # greedy/flat, greedy/nested, greedy/overlap
  - decoder: greedy/overlap

  # focal/1.00, focal/0.75, focal/0.50, focal/0.25, focal/0.00
  - loss: focal/0.50

  # adam
  - optimizer: adam
