_target_: src.models.MoLiNER

defaults:
  # tmr/scratch, tmr/pretrained, tmr/frozen
  - motion_frames_encoder: tmr/scratch
  # deberta/frozen, deberta/pretrained, tmr/scratch, tmr/pretrained, tmr/frozen, clip/frozen, clip/pretrained
  - prompts_tokens_encoder: tmr/scratch

  # windowed/8, windowed/16
  # static/1-16-1, static/1-32-1, static/1-48-1, static/1-64-1, 1-168-8, static/1-208-2, static/1-208-4, static/8-32-1, static/16-64-1, static/32-64-1
  - spans_generator: static/1-32

  # mlp
  - prompt_representation_layer: mlp
  # endpoints
  # convolution/base/16-16-1, convolution/max/16-16-1, convolution/sum/16-16-1, convolution/mean/16-16-1
  - span_representation_layer: endpoints

  # product
  - scorer: product

  # greedy/flat, greedy/nested, greedy/overlap
  - decoder: greedy/overlap

  # focal/1.00, focal/0.75, focal/0.50, focal/0.25, focal/0.00
  - loss: focal/0.50

  # adam
  - optimizer: adam

  # span_grouping/0, span_grouping/4, span_grouping/8
  - postprocessors: span_grouping/8
