_target_: src.model.MoLiNER

lr:
  scratch: 5e-5
  pretrained: 1e-5

defaults:
  # tmr/scratch, tmr/pretrained, tmr/frozen
  - motion_frames_encoder: tmr/scratch
  # deberta/frozen, deberta/pretrained, tmr/scratch, tmr/pretrained, tmr/frozen, clip/frozen, clip/pretrained
  - prompts_tokens_encoder: tmr/scratch

  #  windowed/16, windowed/8, static/1-16, static/1-32, static/8-32
  - spans_generator: static/1-32

  # mlp/deberta, mlp/tmr, mlp/clip
  - prompt_representation_layer: mlp/tmr
  # endpoints, pooling/min, pooling/mean, pooling/max
  # transformer, lstm, convolution
  # query, mlp/1-16, mlp/1-32
  - span_representation_layer: endpoints

  # product
  - scorer: product

  # greedy/flat, greedy/nested, greedy/overlap
  - decoder: greedy/overlap

  # focal
  - loss: focal
