_target_: src.logger.wandb.WandBLogger
project: moliner
name: ${run_dir}
save_dir: ${run_dir}
offline: false
tags: []
notes: "MoLiNER training run"
# NOTE: set to your WandB username or team
entity: nadirkichou-university-of-lille
