_target_: src.model.modules.motion_frames_encoders.tmr.TMRMotionFramesEncoder
weights_path: ./models/tmr_humanml3d_guoh3dfeats/last_weights/motion_encoder.pt
frozen: false
pretrained: false
sample_mean: false
