_target_: src.callbacks.visualization.VisualizationCallback
batch_index: 0
num_samples: 2
# NOTE: can be a single value or list of thresholds
score_threshold: [0.3, 0.5, 0.7]
debug: false
# NOTE: run every 5 epochs instead of every epoch
visualization_frequency: 1
skip_html_generation: false
dirpath: ${run_dir}/visualizations
