defaults:
  - defaults
  - _self_

max_workers: null

configurations:
  - [babel, babel-act-cat, "train,validation"]
  - [babel, babel-proc-label, "train,validation"]
  - [babel, babel, "train,validation"]
  - [babel, locate, "train,validation"]
  - [hml3d, hml3d, "train,validation,test"]