run_dir: ???

share: False
device: auto

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  num_workers: 8

defaults:
  - data: babel
  # - data: locate-babel
  # - data: standardized-chunking-locate-babel
  - model: moliner.base
  - trainer
  - defaults
  - _self_
  - override hydra/launcher: basic
