ckpt: null
# run_dir: null

share: False
device: cuda:1

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  num_workers: 8

defaults:
  - data: babel
  - model: moliner
  - trainer
  - defaults
  - _self_
  - override hydra/launcher: basic
