ckpt: best
resume_dir: null

run_dir: out/training.${now:%Y-%m-%d_%H-%M-%S}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 8
  persistent_workers: True

defaults:
  - data: ???
  - model: ???
  - trainer
  - defaults
  - _self_
  - override hydra/launcher: basic
