_target_: src.model.modules.span_representation_layers.convolution.ConvolutionalSpanRepresentationLayer
motion_embed_dim: 256
representation_dim: 256
min_span_width: 1
max_span_width: 16
shared_weights: false
