_target_: src.model.prompts_tokens_encoders.pretrained_tmr.PretrainedTMRPromptsTokensEncoder
weights_path: /home/nadir/motion-linner/models/tmr_humanml3d_guoh3dfeats/last_weights/text_encoder.pt
finetune: true