_target_: src.model.prompts_tokens_encoders.pretrained_tmr.PretrainedTMRPromptsTokensEncoder
model_path: models/tmr_humanml3d_guoh3dfeats/last_weights/epoch=99-step=47700.ckpt
finetune: true
output_dim: null  # Use the output_dim from the pretrained model
